[package]
name = "hello_cargo"
version = "0.1.0"
edition = "2021"
author = "Paulo Ortolan"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
